name: check for broken links on docs site

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: check for broken links
      uses: ruzickap/action-my-broken-link-checker@v2
      with:
        url: https://www.brimdata.io
        cmd_params: --verbose
                    --timeout 300
                    --buffer-size 8192
                    --max-response-body-size 1000000000
                    --exclude https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf
                    --exclude https://github.com/edgedb/edgedb#-types-not-tables-
                    --exclude https://github.com/brimdata/zed#zed--

#                    --exclude ^https://github.com/brimdata/zed/tree/main/docs/language/.*
#                    --exclude ^https://github.com/brimdata/brim/releases/download.*
#                    --exclude ^https://github.com/brimdata/zed/releases/download.*
#
#                    --exclude linkedin.com
#                    --exclude mixpanel.com
#                    --exclude twitter.com

# For docs production site
#
#        url: https://zed.brimdata.io
#        cmd_params: --buffer-size=8192 --header="Accept-Encoding:zstd,br,gzip,deflate" --exclude algolia.net --exclude www.googletagmanager.com # --verbose
#
# For docs test site
#        url: https://philrz.github.io
#        cmd_params: --buffer-size=8192 --header="Accept-Encoding:zstd,br,gzip,deflate" --exclude algolia.net --exclude www.googletagmanager.com # --verbose
#
#        url: https://www.brimdata.io
#        cmd_params: --verbose --exclude linkedin.com --exclude mixpanel.com --exclude twitter.com --exclude ^https://github.com/brimdata/zed/tree/main/docs/language/.*# --timeout 300
# For brimdata.io
