name: check for broken links on docs site

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: check for broken links
      uses: ruzickap/action-my-broken-link-checker@v2
      with:
        url: https://zed.brimdata.io
        cmd_params: --buffer-size=8192 --exclude algolia.net --exclude www.googletagmanager.com # --verbose
