name: Markdown link check

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/markdown-link-check-config.json
  deployed-wiki-check:
    runs-on: ubuntu-latest
    steps:
    - name: check for broken links on deployed wiki
      uses: ruzickap/action-my-broken-link-checker@v2
      with:
        url: https://github.com/philrz/scratchwiki/wiki
        cmd_params: --verbose --timeout 300

