name: Use a parameter

on:
  workflow_dispatch:
    inputs:
      zui-branch:
        description: 'Zui branch on which to base this Zui Insiders build'
        default: 'main'
        required: false

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
    - name: Output my param
      run: echo "I'd checkout ${{ github.events.inputs.zui-branch }}"
